For the cake :-
1)Non-stick vegetable oil cooking spray
2)3/4 cup of butter
3)3 large eggs
4)1/2 cup of sour cream
5)2 tea spoon pure vanilla extract
6)2 cups of all-purpose flour
7)1 1/2 cup of granulated sugar
8)1/2 cup of packed dark brown sugar
9)3/4 cup of Unsweetened cocoa powder
10)1 1/2 teaspoon of baking soda
11)1  teaspoon of  baking powder
12)1  teaspoon of kosher salt

For the frosting:-
1)1 1/2 cup of bittersweet or semisweet chocolate chips
2)1 cup of heavy cream